### ISSUE TITLE
Need to increase ganularity of disk and create grouping

### ISSUE THREAD

**Issue by jon2100** [rhtools/vminfo-parser#40]
When looking at disk size and migrations, the size of the disk is the main impact on time.
In a large environment having VMs with combined disks from sizes 500G to 40 TB so, when trying to gather the data from an RVTools export, one would have groups of Disk sized with OS type
example:
OS             Count of disk/OS (sum)    size group
CentOS 8            2                                0 - 2 TB
Windows Server 2019   8                     2TB - 10 TB
RHEL 9               5                                10 TB - 20 TB
RHEL 9               2                                20  TB - 40 TB

**Comment by stratus-ss** [comment]
I think the best way to accomplish this would be to rearrange the output for this case

```
Disk Space                 0 - 2 TB        2 - 10 TB         10 - 20 TB         20 - 50 TB        50 - 100 TB     100 - ??? TB
Windows Server        100              150                  90                      50                      10                     1
RHEL                            100              150                  90                      50                      10                     1
Ubuntu                       100              150                  90                      50                      10                     1
SUSE                           100              150                  90                      50                      10                     1
```

I am not sure how much we want to break down by OS version. That might be different charts per OS Heading (Windows, Ubuntu,  RHEL etc)

**Comment by stratus-ss** [comment]
I talked to the original reporter. 
The request is broken down by OS and then again by version. Therefore the above is not feasible

**Comment by stratus-ss** [comment]
This is completed by #64
