### ISSUE TITLE
Humanize Disk Ranges

### ISSUE THREAD

**Issue by csfreak** [rhtools/vminfo-parser#44]
>         "Environment                            prod       \n"
>         "0-200 GB                               5082      \n"
>         "201-400 GB                             12970     \n"
>         "401-600 GB                             5232      \n"
>         "601-900 GB                             6744      \n"
>         "901-1500 GB                            3580      \n"
>         "1501-2000 GB                           658       \n"
>         "2001-3000 GB                           915       \n"
>         "3001-5000 GB                           821       \n"
>         "5001-9000 GB                           1006      \n"
>         "9001-114256 GB                         707"

Current ranges get hard to read with we get above the 1000 GB mark.  We should label ranges in human readable numbers,  so ranges where both numbers fall in the same size should use that size.  In the example above from the test cases,  ranges starting with 1501-2000 GB should be converted to TB.  

To accomplish this,  it might make sense to do this when the mask is applied,  as we still have `lower` and `upper` as ints or possibly have `calculate_disk_space_ranges` return a third value in each tuple as a label.  

While we are at it,  it might make sense to use change that return from a tuple to a dict, where the label is the key, and the value is a tuple of `lower` and `upper`,  then we we go do the sort,  we can use a dictionary lookup rather than converting the string label back to an int for sorting.

**Comment by stratus-ss** [comment]
fixed with #58
